(() => {
  const state = {serverId:'uaro',build:{schema:1,name:'',author:'',class:'lord_knight',base:99,job:70,stats:{STR:1,AGI:1,VIT:1,INT:1,DEX:1,LUK:1},skills:{},gear:{},notes:'',tags:['Solo MVP','PvE'],target:'MVP / Mini-boss'}};
  const $=id=>document.getElementById(id), server=()=>RO_SERVERS[state.serverId], esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])), saveKey='ro-build-planner-saves-v2';
  const classCatalog=window.RO_CLASS_CATALOG||[];
  function className(id){return (classCatalog.find(c=>c.id===id)||{}).name||id}
  function setStatus(t){$('status').textContent=t;$('status').hidden=false;clearTimeout(setStatus.t);setStatus.t=setTimeout(()=>$('status').hidden=true,2400)}
  function activeTab(n){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===n));document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id==='tab-'+n))}
  function initServerSelect(){$('serverSelect').innerHTML=Object.values(RO_SERVERS).map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('serverSelect').value=state.serverId}
  function refreshServerMeta(){const s=server();$('serverName').textContent=s.name;$('serverVersion').textContent=s.version;$('serverSummary').textContent=`Data ${s.dataVersion} • ${s.source}`}
  function currentSkills(){return RO_SKILLS[state.build.class]||[]}
  function skillDb(id){return currentSkills().find(x=>x.id===id)||Object.values(RO_SKILLS).flat().find(x=>x.id===id)}
  function canRaiseSkill(def){return (def.req||[]).every(([id,lv])=>(state.build.skills[id]||0)>=lv)}
  function statCost(from,to){let c=0;for(let v=from;v<to;v++)c+=Math.floor((v-1)/10)+2;return c}
  function statPointsUsed(){return Object.values(state.build.stats).reduce((a,v)=>a+statCost(1,v),0)}
  function renderOverview(){const s=server();$('tab-overview').innerHTML=`<div class="hero"><div class="card"><div class="eyebrow">Build</div><h1>${esc(state.build.name||'Untitled Build')}</h1><p class="muted">${esc(state.build.author?'By '+state.build.author:'No author set')} • ${esc(className(state.build.class))} • Base ${state.build.base} / Job ${state.build.job}</p><div class="chips">${state.build.tags.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}<span class="chip">Target: ${esc(state.build.target)}</span></div><div class="stats-grid" style="margin-top:14px">${Object.entries(state.build.stats).map(([k,v])=>`<div class="stat"><span class="muted">${k}</span><strong>${v}</strong></div>`).join('')}</div><div class="skill-tree-note" style="margin-top:12px">Stat points used: <strong>${statPointsUsed()}</strong> • Formula shell is classic Pre-Renewal and isolated for the calculation engine.</div></div><div class="card"><h3>uaRO server profile</h3><div class="chips"><span class="chip">${esc(s.version)}</span><span class="chip">Rates ${s.rates.baseExp}/${s.rates.jobExp}/${s.rates.drop}</span><span class="chip">99/70</span><span class="chip">Max ASPD ${s.rules.maxAspd}</span><span class="chip">Instant Cast ${s.rules.instantCastDex} DEX</span></div><p class="muted" style="margin-top:12px">This planner uses the server layer for non-standard rules instead of replacing the core database.</p><h3 style="margin-top:16px">Main server systems</h3><div class="chips">${s.features.map(f=>`<span class="chip">${esc(f[1])}</span>`).join('')}</div></div></div><h2 class="section-title">Tracked uaRO changes</h2><div class="change-list">${s.changes.map(c=>`<div class="change"><div class="change-top"><strong>${esc(c.title)}</strong><span class="chip">${esc(c.type)} • ${esc(c.date)}</span></div><span class="muted">${esc(c.text)}</span></div>`).join('')}</div><h2 class="section-title">Useful server commands</h2><div class="command-grid">${s.commands.map(c=>`<div class="command"><code>${esc(c[0])}</code><span>${esc(c[1])}</span></div>`).join('')}</div>`}
  function renderStats(){$('tab-stats').innerHTML=`<div class="card"><div class="toolbar"><div><h2>Stats</h2><div class="muted">Classic stat-cost planner; server limits come from the active dataset.</div></div><select id="classSelect">${classCatalog.map(c=>`<option value="${c.id}" ${c.id===state.build.class?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="grid grid-3">${Object.keys(state.build.stats).map(k=>`<label>${k}<input class="stat-input" data-stat="${k}" type="number" min="1" max="${server().rules.maxStat}" value="${state.build.stats[k]}"></label>`).join('')}</div><div class="grid grid-2" style="margin-top:12px"><label>Base Level<input id="baseLv" type="number" min="1" max="${server().rules.baseMax}" value="${state.build.base}"></label><label>Job Level<input id="jobLv" type="number" min="1" max="${server().rules.jobMax}" value="${state.build.job}"></label></div><div class="skill-tree-note" style="margin-top:12px">Next calculation layer: HP/SP/ATK/MATK/HIT/FLEE/ASPD/CRIT, weapon formulas, refine, cards, element, race, size, boss modifiers and consumables.</div></div>`;$('classSelect').addEventListener('change',e=>{state.build.class=e.target.value;state.build.skills={};renderAll();setStatus('Class changed; skill plan reset')});document.querySelectorAll('.stat-input').forEach(i=>i.addEventListener('input',()=>{state.build.stats[i.dataset.stat]=Math.max(1,Math.min(server().rules.maxStat,+i.value||1));renderOverview()}));$('baseLv').addEventListener('input',e=>{state.build.base=Math.max(1,Math.min(server().rules.baseMax,+e.target.value||1));renderOverview()});$('jobLv').addEventListener('input',e=>{state.build.job=Math.max(1,Math.min(server().rules.jobMax,+e.target.value||1));renderOverview()})}
  function renderSkills(){const list=currentSkills();const used=Object.values(state.build.skills).reduce((a,b)=>a+b,0);$('tab-skills').innerHTML=`<div class="card"><div class="toolbar"><div><h2>Skill Planner</h2><div class="muted">Prerequisites are represented by stable planner IDs. uaRO-only changes override the core definitions.</div></div><div class="points">Used Skill Levels: <strong>${used}</strong></div></div><div class="skill-list">${list.length?list.map(d=>{const lv=state.build.skills[d.id]||0,ok=canRaiseSkill(d);const req=(d.req||[]).map(([rid,rLv])=>`${esc(skillDb(rid)?.name||rid)} ${rLv}`).join(', ');return `<div class="skill ${lv?'changed':''}"><div class="skill-top"><strong>${esc(d.name)}</strong><span>${lv}/${d.max}</span></div><small>${esc(d.group)}${req?` • Req: ${req}`:''}</small><div class="level-control"><button data-skill="${d.id}" data-delta="-1">−</button><div class="level-value">${lv}</div><button data-skill="${d.id}" data-delta="1" ${lv>=d.max||(!ok&&lv===0)?'disabled':''}>+</button></div>${!ok&&lv===0?'<div class="skill-lock">Prerequisite missing</div>':''}</div>`}).join(''):'<div class="skill-tree-note">This class is not populated yet. The database schema is ready; add the class skill list in <code>data/core-pre-renewal/skills.js</code>.</div>'}</div><div class="skill-tree-note" style="margin-top:14px"><strong>Server override example:</strong> uaRO changes such as Lord Knight's Spiral Pierce requirement belong in <code>data/servers/uaro/index.js</code>, not in the generic skill file.</div></div>`;$('tab-skills').querySelectorAll('[data-skill]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.skill,d=skillDb(id),delta=+b.dataset.delta,next=Math.max(0,Math.min(d?.max||10,(state.build.skills[id]||0)+delta));if(delta>0&&!canRaiseSkill(d))return;state.build.skills[id]=next;renderSkills();renderOverview()}))}
  function mergedItems(){const core=Object.values(RO_ITEMS_CORE||{});const custom=server().items||[];const map=new Map(core.map(x=>[String(x.id),x]));custom.forEach(x=>map.set(String(x.id||x.key),x));return [...map.values()]}
  function resolveItem(token){const m=String(token).match(/^@(item|weapon):(.+)$/i);if(!m)return null;const key=m[2];return mergedItems().find(x=>String(x.id||x.key).toLowerCase()===key.toLowerCase())||null}
  function renderGear(){const slots=['Headgear Top','Headgear Middle','Headgear Lower','Armor','Weapon','Shield','Garment','Shoes','Accessory 1','Accessory 2'];$('tab-gear').innerHTML=`<div class="card"><div class="toolbar"><div><h2>Equipment</h2><div class="muted">Enter <code>@item:ID</code> or pick from the current server database.</div></div><button id="insertDemo">Insert @item:1232</button></div><div class="equipment">${slots.map(sl=>`<div class="slot"><div class="slot-name">${esc(sl)}</div><input data-slot="${esc(sl)}" value="${esc(state.build.gear[sl]||'')}" placeholder="@item:1232 or item name"></div>`).join('')}</div><div class="resolved-grid" id="resolvedGear"></div></div>`;$('tab-gear').querySelectorAll('[data-slot]').forEach(i=>i.addEventListener('input',()=>{state.build.gear[i.dataset.slot]=i.value;renderResolvedGear()}));$('insertDemo').addEventListener('click',()=>{state.build.gear.Weapon='@item:1232';renderGear()});renderResolvedGear()}
  function renderResolvedGear(){const arr=Object.entries(state.build.gear).map(([slot,val])=>[slot,val,resolveItem(val)]).filter(x=>x[1]);$('resolvedGear').innerHTML=arr.length?arr.map(([slot,val,item])=>`<div class="resolved"><strong>${esc(slot)}</strong><span>${item?esc(item.name):esc(val)}</span>${item?`<small>${esc(item.type||'Item')} ${item.id?'• DB ID '+item.id:''}${item.custom?' • uaRO custom':''}</small>`:'<small class="muted">No database match yet</small>'}</div>`).join(''):'<div class="skill-tree-note">No equipment assigned yet.</div>'}
  function renderDatabase(){const items=mergedItems();$('tab-database').innerHTML=`<div class="card"><div class="toolbar"><div><h2>uaRO Database</h2><div class="muted">Initial content only. Core and server layers are deliberately separate so a real DB can replace these records later.</div></div><input id="dbSearch" class="db-search" placeholder="Search item, command, system, skill..."></div><div class="db-tabs"><button data-db="items" class="active">Items</button><button data-db="skills">Skills</button><button data-db="commands">Commands</button><button data-db="systems">Systems</button><button data-db="changes">Changes</button></div><div id="dbResults"></div></div>`;renderDbResults('items',items);document.querySelectorAll('[data-db]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-db]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDbResults(b.dataset.db,items)}));$('dbSearch').addEventListener('input',()=>{const active=document.querySelector('[data-db].active')?.dataset.db||'items';renderDbResults(active,items)})}
  function renderDbResults(kind,items){const q=($('dbSearch')?.value||'').toLowerCase().trim();let html='';if(kind==='items'){const rows=items.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).slice(0,80);html=rows.map(x=>`<div class="db-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.type||'Item')} ${x.id?'• ID '+x.id:''}${x.custom?' • uaRO':''}</small></div><div class="db-effects">${(x.effects||[]).slice(0,3).map(y=>esc(y)).join(' • ')}</div></div>`).join('')}else if(kind==='skills'){const rows=Object.values(RO_SKILLS).flat().filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).slice(0,100);html=rows.map(x=>`<div class="db-row"><div><strong>${esc(x.name)}</strong><small>${esc(x.id)} • ${esc(x.group)} • max ${x.max}</small></div><div class="db-effects">${(x.req||[]).map(r=>esc((skillDb(r[0])||{}).name||r[0])+' '+r[1]).join(' • ')||'No prerequisites listed in this initial catalog'}</div></div>`).join('')}else if(kind==='commands'){html=server().commands.filter(x=>!q||x.join(' ').toLowerCase().includes(q)).map(x=>`<div class="db-row"><div><code>${esc(x[0])}</code></div><div class="db-effects">${esc(x[1])}</div></div>`).join('')}else if(kind==='systems'){html=server().features.filter(x=>!q||x.join(' ').toLowerCase().includes(q)).map(x=>`<div class="db-row"><div><strong>${esc(x[1])}</strong><small>${esc(x[0])}</small></div><div class="db-effects">uaRO server system</div></div>`).join('')}else{html=server().changes.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).map(x=>`<div class="db-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.type)} • ${esc(x.date)}</small></div><div class="db-effects">${esc(x.text)}</div></div>`).join('')}$('dbResults').innerHTML=html||'<div class="skill-tree-note">No matching records.</div>'}
  function parseTokens(text){const tokenRe=/@(item|weapon|skill|mob|quest|system):([A-Za-z0-9_:-]+)/g;return text.replace(tokenRe,(all,type,id)=>{let obj=null; if(type==='item'||type==='weapon')obj=resolveItem('@item:'+id); if(type==='skill')obj=skillDb(id); if(!obj)return all; const label=obj.name||id; return `<span class="token" title="${esc(tokenTooltip(obj))}">${esc(label)}</span>`})}
  function tokenTooltip(o){if(o.type==='Headgear'||o.type==='Weapon'||o.type==='Armor'||o.type==='Accessory'||o.type==='Consumable')return [o.name,o.type,o.id?'DB ID '+o.id:'',...(o.effects||[])].filter(Boolean).join(' • ');return [o.name,o.group?'Group '+o.group:'',o.max?'Max '+o.max:''].filter(Boolean).join(' • ')}
  function renderNotes(){$('tab-notes').innerHTML=`<div class="card"><h2>Build Notes</h2><p class="muted">Write your complete build here. The saved format stays plain text. When the database grows, tokens can resolve into hover information without changing old builds.</p><textarea id="notesArea" placeholder="Leveling path, farming targets, gear progression, MVP notes, skill reasoning...">${esc(state.build.notes)}</textarea><div class="skill-tree-note" style="margin-top:10px"><strong>Token examples:</strong> <code>@item:1232</code> <code>@skill:back_stab</code> <code>@mob:1513</code> <code>@quest:dim_advanced_assassin_mask</code> <code>@system:poring_coin</code></div><div class="preview-card" id="notePreview"><div class="eyebrow">Rendered preview</div><div id="renderedNotes"></div></div></div>`;$('notesArea').addEventListener('input',e=>{state.build.notes=e.target.value;renderNotesPreview()});renderNotesPreview()}
  function renderNotesPreview(){const e=$('renderedNotes');if(e)e.innerHTML=state.build.notes?parseTokens(esc(state.build.notes)).replace(/\n/g,'<br>'):'<span class="muted">Nothing written yet.</span>'}
  function previewHTML(){const b=state.build;return `<div class="preview-inner"><div class="eyebrow">RO BUILD PLANNER • ${esc(server().name)}</div><div class="preview-title">${esc(b.name||'Untitled Build')}</div><div class="muted">${esc(className(b.class))} • Base ${b.base} / Job ${b.job} • ${esc(b.target)}</div><div class="chips" style="margin-top:14px">${b.tags.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><div class="stats-grid" style="margin-top:14px">${Object.entries(b.stats).map(([k,v])=>`<div class="stat"><span class="muted">${k}</span><strong>${v}</strong></div>`).join('')}</div><div class="muted" style="margin-top:14px">${Object.entries(b.skills).filter(([,v])=>v).map(([k,v])=>`${esc(skillDb(k)?.name||k)} ${v}`).join(' • ')||'No skills planned yet'}</div></div>`}
  function renderShare(){$('tab-share').innerHTML=`<div class="card"><h2>Share</h2><p class="muted">Builds can be encoded into the URL now. Later, the same schema can be saved server-side as a permanent build record.</p><button id="openShareInline" class="primary">Generate share package</button></div>`;$('openShareInline').addEventListener('click',openShare)}
  function encodeBuild(){return btoa(unescape(encodeURIComponent(JSON.stringify({v:1,server:state.serverId,build:state.build})))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
  function decodeBuild(raw){try{raw=raw.replace(/-/g,'+').replace(/_/g,'/');while(raw.length%4)raw+='=';return JSON.parse(decodeURIComponent(escape(atob(raw))))}catch{return null}}
  function shareUrl(){return location.href.split('#')[0]+'#build='+encodeBuild()}
  function openShare(){const url=shareUrl();$('shareUrl').value=url;$('markdownOut').value=`[${state.build.name||'RO Build'}](${url})`;const note=`RO Build: ${state.build.name||'Untitled'} | ${className(state.build.class)} | Base ${state.build.base}/Job ${state.build.job}`;$('bbcodeOut').value=`[URL=${url}][B]${state.build.name||'RO Build'}[/B][/URL]\n${note}\n[B]Stats[/B]: ${Object.entries(state.build.stats).map(([k,v])=>`${k} ${v}`).join(' • ')}`;$('sharePreview').innerHTML=previewHTML();$('shareDialog').showModal()}
  async function copy(v){try{await navigator.clipboard.writeText(v);setStatus('Copied to clipboard')}catch{setStatus('Clipboard is unavailable in this browser')}}
  function downloadPreview(){const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#11151c"/><rect x="40" y="40" width="1120" height="550" rx="26" fill="#1b2531"/><text x="75" y="95" fill="#8fa3b9" font-family="Arial" font-size="22">RO BUILD PLANNER • ${esc(server().name)}</text><text x="75" y="160" fill="#eef1f5" font-family="Arial" font-size="52" font-weight="700">${esc(state.build.name||'Untitled Build')}</text><text x="75" y="205" fill="#aab3bf" font-family="Arial" font-size="24">${esc(className(state.build.class))} • Base ${state.build.base} / Job ${state.build.job}</text><text x="75" y="250" fill="#93a2b4" font-family="Arial" font-size="20">${esc(state.build.target)}</text><text x="75" y="330" fill="#eef1f5" font-family="Arial" font-size="26">${Object.entries(state.build.stats).map(([k,v])=>`${k} ${v}`).join('    ')}</text><text x="75" y="390" fill="#93a2b4" font-family="Arial" font-size="19">${Object.entries(state.build.skills).filter(([,v])=>v).map(([k,v])=>`${esc(skillDb(k)?.name||k)} ${v}`).join(' • ')||'No skills planned yet'}</text></svg>`;const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1200;c.height=630;c.getContext('2d').drawImage(img,0,0);c.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ro-build-preview.png';a.click();setStatus('Preview PNG exported')},'image/png')};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg)}
  function saveBuild(){const list=JSON.parse(localStorage.getItem(saveKey)||'[]');const now=new Date().toISOString();const item={id:crypto.randomUUID(),updated:now,server:state.serverId,build:JSON.parse(JSON.stringify(state.build))};list.unshift(item);localStorage.setItem(saveKey,JSON.stringify(list.slice(0,50)));setStatus('Build saved locally')}
  function showLoads(){const list=JSON.parse(localStorage.getItem(saveKey)||'[]');$('savedBuilds').innerHTML=list.length?list.map(x=>`<div class="saved-row"><div><strong>${esc(x.build.name||'Untitled')}</strong><small>${esc(x.server)} • ${esc(className(x.build.class))} • ${new Date(x.updated).toLocaleString()}</small></div><div><button data-load="${x.id}">Load</button><button data-del="${x.id}" class="danger">Delete</button></div></div>`).join(''):`<div style="padding:16px" class="muted">No saved builds yet.</div>`;$('loadDialog').showModal();document.querySelectorAll('[data-load]').forEach(b=>b.addEventListener('click',()=>{const x=list.find(y=>y.id===b.dataset.load);if(x){state.serverId=x.server;state.build=x.build;refresh();$('loadDialog').close();setStatus('Build loaded')}}));document.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',()=>{localStorage.setItem(saveKey,JSON.stringify(list.filter(y=>y.id!==b.dataset.del)));showLoads()}))}
  function refresh(){initServerSelect();$('buildName').value=state.build.name;$('author').value=state.build.author;refreshServerMeta();renderAll()}
  function renderAll(){renderOverview();renderStats();renderSkills();renderGear();renderDatabase();renderNotes();renderShare()}
  function readHash(){const m=location.hash.match(/^#build=(.+)$/);if(!m)return;const x=decodeBuild(m[1]);if(x?.build){state.serverId=x.server||'uaro';state.build=x.build;setStatus('Shared build loaded from URL')}}
  document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>activeTab(b.dataset.tab)));$('serverSelect').addEventListener('change',e=>{state.serverId=e.target.value;state.build.class=server().id==='uaro'?'lord_knight':state.build.class;state.build.skills={};refresh();setStatus('Server dataset changed')});$('buildName').addEventListener('input',e=>{state.build.name=e.target.value;renderOverview()});$('author').addEventListener('input',e=>{state.build.author=e.target.value;renderOverview()});$('newBuildBtn').addEventListener('click',()=>{state.build={schema:1,name:'',author:'',class:'lord_knight',base:1,job:1,stats:{STR:1,AGI:1,VIT:1,INT:1,DEX:1,LUK:1},skills:{},gear:{},notes:'',tags:['Solo MVP','PvE'],target:'MVP / Mini-boss'};refresh();setStatus('New build created')});$('saveBtn').addEventListener('click',saveBuild);$('loadBtn').addEventListener('click',showLoads);$('shareBtn').addEventListener('click',openShare);$('closeShare').addEventListener('click',()=>$('shareDialog').close());$('copyUrl').addEventListener('click',()=>copy($('shareUrl').value));$('copyMarkdown').addEventListener('click',()=>copy($('markdownOut').value));$('copyBBCode').addEventListener('click',()=>copy($('bbcodeOut').value));$('downloadPreview').addEventListener('click',downloadPreview);readHash();refresh();
})();
